"""add_spreadsheet_tracking_columns

Revision ID: 708e79ba2898
Revises: 998cbe72a0c0
Create Date: 2026-09-28 05:29:11.555721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708e79ba2898'
down_revision: Union[str, Sequence[str], None] = '998cbe72a0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_profiles', sa.Column('spreadsheet_id', sa.String(length=255), nullable=True))
    op.add_column('resume_profiles', sa.Column('spreadsheet_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_resume_profiles_spreadsheet_id'), 'resume_profiles', ['spreadsheet_id'], unique=False)
    op.add_column('resumes', sa.Column('spreadsheet_id', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('spreadsheet_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_resumes_spreadsheet_id'), 'resumes', ['spreadsheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_spreadsheet_id'), table_name='resumes')
    op.drop_column('resumes', 'spreadsheet_url')
    op.drop_column('resumes', 'spreadsheet_id')
    op.drop_index(op.f('ix_resume_profiles_spreadsheet_id'), table_name='resume_profiles')
    op.drop_column('resume_profiles', 'spreadsheet_url')
    op.drop_column('resume_profiles', 'spreadsheet_id')
    # ### end Alembic commands ###
