"""add_structured_data_to_resume_profiles

Revision ID: 998cbe72a0c0
Revises: 297273612a76
Create Date: 2026-09-28 05:22:06.386050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '998cbe72a0c0'
down_revision: Union[str, Sequence[str], None] = '297273612a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_profiles', sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_profiles', 'structured_data')
    # ### end Alembic commands ###
