"""initial_schema

Revision ID: e9efc099157b
Revises: 
Create Date: 2026-09-28 11:27:32.444375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9efc099157b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('careers_url', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=True)
    op.create_table('error_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_events_error_code'), 'error_events', ['error_code'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('adapter_class', sa.String(length=128), nullable=True),
    sa.Column('policy', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_state', sa.String(length=32), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_name'), 'job_sources', ['name'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_index(op.f('ix_skills_normalized_name'), 'skills', ['normalized_name'], unique=True)
    op.create_table('system_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_component'), 'system_events', ['component'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('total_checked', sa.Integer(), nullable=False),
    sa.Column('total_active', sa.Integer(), nullable=False),
    sa.Column('total_closed', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('normalized_location', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.String(length=32), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=False),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('application_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'dedup_key', name='uq_jobs_resume_dedup_key')
    )
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_dedup_key'), 'jobs', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_jobs_normalized_title'), 'jobs', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_jobs_resume_id'), 'jobs', ['resume_id'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index('ix_jobs_title_company', 'jobs', ['title', 'company'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_company_id'), 'people', ['company_id'], unique=False)
    op.create_index(op.f('ix_people_normalized_name'), 'people', ['normalized_name'], unique=False)
    op.create_table('resume_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('seniority_level', sa.String(length=32), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=False),
    sa.Column('work_modes', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_profiles_resume_id'), 'resume_profiles', ['resume_id'], unique=True)
    op.create_table('resume_skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('proficiency', sa.String(length=32), nullable=True),
    sa.Column('years_of_experience', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_id', name='uq_resume_skills_resume_skill')
    )
    op.create_index(op.f('ix_resume_skills_resume_id'), 'resume_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skills_skill_id'), 'resume_skills', ['skill_id'], unique=False)
    op.create_table('search_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('total_discovered', sa.Integer(), nullable=False),
    sa.Column('total_verified', sa.Integer(), nullable=False),
    sa.Column('total_matched', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_runs_resume_id'), 'search_runs', ['resume_id'], unique=False)
    op.create_table('sheets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=128), nullable=False),
    sa.Column('spreadsheet_url', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheets_resume_id'), 'sheets', ['resume_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_id', name='uq_applications_resume_job')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_table('job_identifiers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('identifier_type', sa.String(length=64), nullable=False),
    sa.Column('identifier_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'identifier_type', 'identifier_value', name='uq_job_identifiers')
    )
    op.create_index(op.f('ix_job_identifiers_identifier_type'), 'job_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_job_identifiers_identifier_value'), 'job_identifiers', ['identifier_value'], unique=False)
    op.create_index(op.f('ix_job_identifiers_job_id'), 'job_identifiers', ['job_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('match_level', sa.String(length=32), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('why_it_matches', sa.Text(), nullable=True),
    sa.Column('semantic_assessment', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_id', name='uq_job_matches_resume_job')
    )
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_resume_id'), 'job_matches', ['resume_id'], unique=False)
    op.create_table('job_people',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'person_id', name='uq_job_people_job_person')
    )
    op.create_index(op.f('ix_job_people_job_id'), 'job_people', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_people_person_id'), 'job_people', ['person_id'], unique=False)
    op.create_table('job_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_snapshots_job_id'), 'job_snapshots', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_snapshots_snapshot_hash'), 'job_snapshots', ['snapshot_hash'], unique=False)
    op.create_table('job_verification_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_verification_events_job_id'), 'job_verification_events', ['job_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('search_run_id', sa.String(length=32), nullable=False),
    sa.Column('query_text', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_search_run_id'), 'search_queries', ['search_run_id'], unique=False)
    op.create_table('sheet_sync_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sheet_id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_sync_events_resume_id'), 'sheet_sync_events', ['resume_id'], unique=False)
    op.create_index(op.f('ix_sheet_sync_events_sheet_id'), 'sheet_sync_events', ['sheet_id'], unique=False)
    op.create_table('source_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('search_run_id', sa.String(length=32), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_runs_search_run_id'), 'source_runs', ['search_run_id'], unique=False)
    op.create_index(op.f('ix_source_runs_source_name'), 'source_runs', ['source_name'], unique=False)
    op.create_table('application_status_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=False),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_table('job_missing_skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_match_id', sa.String(length=32), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('importance', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['job_match_id'], ['job_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_missing_skills_job_match_id'), 'job_missing_skills', ['job_match_id'], unique=False)
    op.create_index(op.f('ix_job_missing_skills_skill_name'), 'job_missing_skills', ['skill_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_missing_skills_skill_name'), table_name='job_missing_skills')
    op.drop_index(op.f('ix_job_missing_skills_job_match_id'), table_name='job_missing_skills')
    op.drop_table('job_missing_skills')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index(op.f('ix_source_runs_source_name'), table_name='source_runs')
    op.drop_index(op.f('ix_source_runs_search_run_id'), table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index(op.f('ix_sheet_sync_events_sheet_id'), table_name='sheet_sync_events')
    op.drop_index(op.f('ix_sheet_sync_events_resume_id'), table_name='sheet_sync_events')
    op.drop_table('sheet_sync_events')
    op.drop_index(op.f('ix_search_queries_search_run_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_job_verification_events_job_id'), table_name='job_verification_events')
    op.drop_table('job_verification_events')
    op.drop_index(op.f('ix_job_snapshots_snapshot_hash'), table_name='job_snapshots')
    op.drop_index(op.f('ix_job_snapshots_job_id'), table_name='job_snapshots')
    op.drop_table('job_snapshots')
    op.drop_index(op.f('ix_job_people_person_id'), table_name='job_people')
    op.drop_index(op.f('ix_job_people_job_id'), table_name='job_people')
    op.drop_table('job_people')
    op.drop_index(op.f('ix_job_matches_resume_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_job_identifiers_job_id'), table_name='job_identifiers')
    op.drop_index(op.f('ix_job_identifiers_identifier_value'), table_name='job_identifiers')
    op.drop_index(op.f('ix_job_identifiers_identifier_type'), table_name='job_identifiers')
    op.drop_table('job_identifiers')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_sheets_resume_id'), table_name='sheets')
    op.drop_table('sheets')
    op.drop_index(op.f('ix_search_runs_resume_id'), table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_index(op.f('ix_resume_skills_skill_id'), table_name='resume_skills')
    op.drop_index(op.f('ix_resume_skills_resume_id'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_resume_profiles_resume_id'), table_name='resume_profiles')
    op.drop_table('resume_profiles')
    op.drop_index(op.f('ix_people_normalized_name'), table_name='people')
    op.drop_index(op.f('ix_people_company_id'), table_name='people')
    op.drop_table('people')
    op.drop_index('ix_jobs_title_company', table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_resume_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_normalized_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_dedup_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_component'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_skills_normalized_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_sources_name'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_error_events_error_code'), table_name='error_events')
    op.drop_table('error_events')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
